# This config file is meant for settings that affect your whole blog, values which you are expected to set up once and rarely edit after that. If you find yourself editing this file very often, consider using Jekyll's data files feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/


# Site settings
# These are used to personalize your new site. If you look in the HTML files, you will see them accessed via {{ site.title }}, {{ site.tagline }}, and so on. You can create any custom variable you would like, and they will be accessible in the templates via {{ site.myvariable }}.

url:            https://carterpape.com
title:          Carter Pape's website
tagline:        |
    Carter Pape is a reporter  
    for *The Times-Independent*  
    in Moab, Utah.
author:         Carter Pape
lang:           en-us

cloudflare_token: e0a891b5512949ac844da72b444e0b9b

collections:
    journalism:
        output: false
        order:
            - hb-224-intent.md
            - housing-series.md
            - fox-in-mill-creek.md
            - free-reduced-meals.md
            - first-hdho-story.md
            - hopkin.md
    apps:
        output: false
        order:
            - moab.news.md
            - newsbot.md
            - moabtimes.com.md
            - praeci.md
            - genetic-optimization.md
    awards:
        output: false
        order:
            - best-gov-pol-story.md
            - best-general-news.md
            - best-education-story.md
            - best-website.md
            - model-the-way.md
            - best-podcast.md
            - best-audio-documentary.md
    references:
        output: false
        order:
            - doug.md
            - zane.md
            - jamie.md
            - jonathan.md

# Formatting settings

permalink:      /:categories/:title
timezone:       America/Denver
date_format:    "%b. %-d, %Y"

defaults:
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "browsing/page"
    -
        scope:
            path: ""
            type: "posts"
        values:
            author: Carter Pape
            layout: "reading/post"
            unlisted: false
            featured_image:
                same_as_social_image: true
    -
        scope:
            path: "the-blog/unlisted"
            type: "posts"
        values:
            unlisted: true
            sitemap:
                exclude: true

kramdown:
    footnote_backlink: "â¤´"
    auto_ids: true
    auto_id_stripping: true

category_display_names:
    the-blog:               "the blog"
    making-carterpape-com:  "making carterpape.com"
    decompiling-facebook:   "decompiling Facebook"
    making-write:           "making write"

# Build settings

lsi:        true
livereload: true
open_url:   true

liquid:
    error_mode:         strict
    strict_variables:   false
    strict_filters:     true

strict_front_matter: true

sass:
    implementation: sass-embedded
    style: compressed
    sass_dir: _scss

jekyll-minifier:
    compress_css: false
    compress_javascript: false

reduce_title_redundancy:
    strip_title: true

# Exclude from processing.
# The following items will not be processed, by default. Any item listed under the `exclude:` key here will be automatically added to the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or their entries' file path in the `include:` list.

exclude:
    - .sass-cache/
    - .jekyll-cache/
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - node_modules/
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - .gitignore
    - s3_website.yml
    - .env
    - moab.news
    - scripts/
    - README.md
    - LICENSE
