url: "https://carterpape.com/"
title: "Carter Pape's personal website"

author:
    name: "Carter Pape"
    short_description: "Carter Pape is a freelance writer and developer seeking full-time work in journalism"
    email: "carterpape@gmail.com"
    linkedin_url: "https://www.linkedin.com/in/carter-pape/"
    twitter_url: "https://twitter.com/cartrpape"
    photo:
        path: "/assets/images/Carter-Pape.jpg"
        title: "Carter in front of Winslow Hall"
        alt: "Carter stands in front of Winslow Hall on campus at NC State."

timezone: America/New_York
lang: en-us

permalink: /:categories/:title
defaults:
    -
        scope:
            path: "the-blog"
            type: "posts"
        values:
            authors: ["Carter Pape"]
            layout: "reading/post"
            unlisted: false
    -
        scope:
            path: "the-blog/unlisted"
            type: "posts"
        values:
            unlisted: yes

plugins:
    - jekyll-redirect-from

kramdown:
    footnote_backlink: "â¤´"

exclude: ["writing aids/*"]